name: Build C++20

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: x64

      - name: Build solution
        run: >
          msbuild "Puissance 4.sln"
          /m
          /t:Build
          /p:Configuration=Release
          /p:Platform=x64
          /verbosity:minimal